### ISSUE TITLE
Simba "package" install capability

### ISSUE THREAD

**Issue by BrettMoan** [Brandon-T/Reflection#31]
@olly's package manager works smoothly for the SRL installs. And I think It would make installing reflect for a lot easier if the project files were organized in such a way, that people could use the package-manager.

Then people could update just by using Simba's built-in features instead of re-cloning the project from source.

About a year ago i did a PR for this, but i recently closed in since it was WAY out of date. basically you just have to move some files around though, and add the simba package file that is found in the SRL projects.

**Comment by Brandon-T** [comment]
Done. The include is now installed as a package.
Plugins still have to be done manually (I added a script that will download them and install them though). Might have to find a different way of doing that.
