### ISSUE TITLE
If chat option is not found it goes to free and causes an access violation.

### ISSUE THREAD

**Issue by darxper** [Brandon-T/Reflection#6]
https://github.com/Brandon-T/Reflection/blob/556ac51a828d7a1bdd2736891f7ef70e6497def1/Reflection/Chat.simba#L153

**Comment by Brandon-T** [comment]
Should be fixed in `https://github.com/Brandon-T/Reflection/commit/8da83ff2b1ad237f1fd9913f39b48fb705004f16`
